# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Build extension
      run: pnpm run build --if-present

    - name: Zip extension
      run: zip -r ypm-${{ github.sha }}.zip dist

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: ypm-${{ github.sha }}.zip
